# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: 'temurin'

      - name: Setup Maven settings (单独配置 server-id 等)
        uses: s4u/maven-settings-action@v4.0.0
        with:
          servers: |
            [
              {
                "id": "github",
                "username": "${{ github.actor }}",
                "password": "${{ secrets.GITHUB_TOKEN }}"
              },
              {
                "id": "sonatype",
                "username": "${{ secrets.MAVEN_USERNAME }}",
                "password": "${{ secrets.MAVEN_PASSWORD }}"
              }
            ]

      - name: Deploy snapshot to github
        run: mvn -P github --batch-mode deploy

      - name: Deploy sonatype to sonatype
        run: mvn -P sonatype --batch-mode deploy
